Description: Deploy an memcache cluster
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Some Configuration"
        Parameters:
          - ElasticCacheSubnets
          - CacheSecurityGroupNames
          - ClusterName
          - CacheNodeType
Parameters:
  ElasticCacheSubnets:
    Description: EC Subnet ID
    Type: "List<AWS::EC2::Subnet::Id>"
  CacheNodeType:
    Description: Node Type
    Type: String
    AllowedValues: ["cache.r4.large", "cache.r4.xlarge", "cache.r4.2xlarge", "cache.r4.4xlarge", "cache.r4.8xlarge", "cache.r4.16xlarge"]
  CacheSecurityGroupNames:
    Description: SecurityGroupNames
    Type: "List<AWS::EC2::SecurityGroup::Id>"
  ClusterName:
    Description: Cluster Name
    Type: String
Resources:
  ElasticCacheSubnetGroup:
    Type: AWS::ElastiCache::SubnetGroup
    Properties:
      CacheSubnetGroupName: memcacheSubnets
      Description: CacheSubnetGroup
      SubnetIds: !Ref ElasticCacheSubnets
  ElastiCacheCluster:
    Type: AWS::ElastiCache::CacheCluster
    Properties: 
      CacheNodeType: !Ref CacheNodeType
      CacheSubnetGroupName: !Ref ElasticCacheSubnetGroup
      ClusterName: !Ref ClusterName
      Engine: redis
      NumCacheNodes: 1
      Port: 6379
      VpcSecurityGroupIds: !Ref CacheSecurityGroupNames